calc_passwd:
  name: Calculate passwd
  description: Calculate default passwd.
  target:
    device:
      integration: miwifi

request:
  name: Send request
  description: Send request to router.
  target:
    device:
      integration: miwifi
  fields:
    uri:
      name: Uri
      description: Request uri.
      required: true
      example: "misystem/led"
      selector:
        text:
    body:
      name: Body
      description: Request body.
      required: false
      example: |
        on: 1
      selector:
        object:
          
block_device:
  name: "Block Device"
  description: "Enable or disable WAN access for a connected device (MiWiFi Router)."
  fields:
    device_id:
      name: Device
      description: "Select the device you want to block or unblock from internet access."
      required: true
      selector:
        device:
          integration: miwifi
          entity:
            domain: device_tracker
    allow:
      name: Allow Internet Access
      description: "Select 'On' to allow WAN access, or 'Off' to block WAN access for the selected device."
      required: true
      selector:
        boolean:


dump_router_data:
  name: Dump Router Data
  description: Generate a JSON file with router information.
  fields:
    system:
      name: Include system data
      description: Include system information.
      default: true
      selector:
        boolean: {}
    network:
      name: Include network data
      description: Include WAN, Wi-Fi and topology details.
      default: true
      selector:
        boolean: {}
    devices:
      name: Include connected devices
      description: Include list of connected devices.
      default: true
      selector:
        boolean: {}
    nat_rules:
      name: Include NAT rules
      description: Include port forwarding rules.
      default: true
      selector:
        boolean: {}
    qos:
      name: Include QoS configuration
      description: Include QoS bandwidth settings.
      default: true
      selector:
        boolean: {}
    wifi_config:
      name: Include Wi-Fi configuration
      description: Include Wi-Fi network settings (may contain sensitive data).
      default: false
      selector:
        boolean: {}
    hide_sensitive:
      name: Hide sensitive data
      description: Hide passwords and MAC addresses.
      default: true
      selector:
        boolean: {}
